import ImportCSVButton from "components/passive-income/ImportCsvButton";
import { useMemo } from "react";
import { Accordion, Alert, Button, Form, ListGroup } from "react-bootstrap";
import { SecurityDataProvider } from "shared/types/passive-income-types";

type PropType = {
  apiKey: string;
  provider: SecurityDataProvider;
  onAddHolding: () => void;
  onApiKeyChange: (key: string) => void;
  onImportError: (error: string) => void;
  onImportHoldings: (holdings: Array<any>) => void;
  onProviderChange: (provider: SecurityDataProvider) => void;
};

export default function PortfolioHeader({
  apiKey,
  provider,
  onAddHolding,
  onApiKeyChange,
  onImportError,
  onImportHoldings,
  onProviderChange,
}: PropType) {
  const isAddHoldingButtonDisabled = useMemo(
    () => provider === SecurityDataProvider.ALPHA_VANTAGE && !apiKey,
    [apiKey, provider]
  );

  return (
    <ListGroup>
      <ListGroup.Item>
        <Accordion as={Alert} defaultActiveKey="0" variant="info">
          <Accordion.Item eventKey="0">
            <Accordion.Header>About this tool</Accordion.Header>
            <Accordion.Body>
              <ul>
                <li>
                  This tool helps you manage your dividend portfolio by fetching
                  real-time data from <code>Alpha Vantage</code> API, and using
                  the data to estimate your annual income and yield.
                </li>
                <li>
                  This page is mostly generated by ChatGPT, with some manual
                  fine tunes or additions.
                </li>
                <li>
                  You could use either <code>Alpha Vantage</code> or{" "}
                  <code>Yahoo! Finance</code> API to fetch the stock data
                  required to compute the dividend income.
                </li>
                <li>
                  If you choose <code>Alpha Vantage</code> API, then enter your
                  <code>Alpha Vantage</code> API key below before providing your
                  input.
                  <ul>
                    <li>
                      Go to{" "}
                      <a
                        href="https://www.alphavantage.co/support/#api-key"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        https://www.alphavantage.co/support/#api-key
                      </a>{" "}
                      to obtain a free API key.
                    </li>
                    <li>
                      However, they limit to 25 requests per day, so please plan
                      your usage accordingly or get a premium access.
                    </li>
                  </ul>
                </li>
                <li>
                  Unfortunately, <code>Yahoo! Finance</code> will not allow
                  fetching from the client due to cross-origin policy, so the
                  call has to be made through a server-side wrapper. To avoid
                  overloading the wrapper, only those with an authorized key can
                  use the API.
                </li>
                <li>
                  If you want to import a CSV,{" "}
                  <strong>make sure it follows the correct format</strong>:
                  <ul>
                    <li>
                      Column headers must include:{" "}
                      <code>
                        Symbol, Number of Shares, Cost Basis, Category
                      </code>
                    </li>
                    <li>
                      You could start with{" "}
                      <a href="/passive-income/test-import-file.csv">
                        this sample file
                      </a>
                      .
                    </li>
                  </ul>
                </li>
                <li>
                  The data is yours to keep, this website does not keep any
                  records of your API key nor the data you have retrieved or
                  provided.
                  <ul>
                    <li>
                      <code>Alpha Vantage/Yahoo! Finance</code> is the only API
                      call this website makes to fetch the security data. All
                      other computations are done on the client side.
                    </li>
                  </ul>
                </li>
                <li>
                  If you want to keep the data for future use, please use the{" "}
                  <code>Export (under development)</code> function before
                  leaving the page. Otherwise, you will loss the data.
                </li>
              </ul>
            </Accordion.Body>
          </Accordion.Item>
        </Accordion>
      </ListGroup.Item>
      <ListGroup.Item variant="light">
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "end",
            gap: "8px",
          }}
        >
          <Form.Group className="mb-3">
            <Form.Select
              value={provider}
              onChange={(e) =>
                onProviderChange(e.target.value as SecurityDataProvider)
              }
              style={{
                width: "200px",
              }}
            >
              {Object.values(SecurityDataProvider).map((label) => (
                <option value={label} key={label}>
                  {label}
                </option>
              ))}
            </Form.Select>
          </Form.Group>
          <Form.Group className="mb-3">
            <Form.Control
              style={{ width: "300px" }}
              type="type"
              placeholder="API key"
              value={apiKey}
              onChange={(e) => onApiKeyChange(e.target.value)}
            />
          </Form.Group>
          <Button
            disabled={isAddHoldingButtonDisabled}
            onClick={onAddHolding}
            className="mb-3"
          >
            + Add Holding
          </Button>
          <ImportCSVButton
            isDisabled={isAddHoldingButtonDisabled}
            onConfirm={onImportHoldings}
            onError={onImportError}
          />
        </div>
      </ListGroup.Item>
    </ListGroup>
  );
}
