import {
  GameVersion,
  MapItem,
  MapTutorial,
  ReleaseStatus,
} from "shared/types/cs-map-types";

export const mapItems: Array<MapItem> = [
  {
    id: 201,
    categoryId: 3,
    name: "de_taxi_plaza",
    fullName: "Battle at Plaza",
    version: "0.01",
    releaseDate: "2023-10-22",
    status: ReleaseStatus.InProgress,
    maxPlayers: 10,
    icon: "/csmaps/icon201.jpg",
    targetGameVersion: GameVersion.COUNTER_STRIKE_2,
    images: [
      {
        url: "https://live.staticflickr.com/65535/53281318131_69bae20cbe_b.jpg",
        caption: "Prototype",
      },
    ],
    downloadLinks: [],
    progressPercentage: 1,
  },
];

export const mapTutorials: Array<MapTutorial> = [
  {
    title: "Play your own addon/workshop map",
    hashKey: "play-your-own-addon-map",
    content: `
### Updated on 2023-12-26
Valve published an update to enable playing Workshop/addon maps without any hacks.

Once you build the map from Hammer, simply launch the default CS2, open the console and use the command below to play the map.

\`\`\`
map_workshop <workshop-id> <map-name>
\`\`\`

\`<workshop-id>\` and \`<map-name>\` are the same if you have not published the map to Steam Workshop yet, CS2 should be able to autocomplete both the ID and the name for you.

By default, the map will be launched in Competitive mode. If you want to launch the map in a different mode (e.g. Casual),
then use the following commands to set the relevant parameters before executing the \`map_workshop\` command.
\`\`\`
game_type <type-number>
game_mode <mode-number>
\`\`\`

Refer to [this table](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive/Game_Modes#Game_Type_and_Game_Mode) for a list of possible game types and mode numbers.

**============== Ignore the section below if you have already installed the latest version of CS2 ==============**

### Introduction
By default, the map your built from Hammer would only be available from the CS2 launched as part of the Workshop Tools.
It will not be available in the normal/release version of CS2.

There are some steps that we need to take in order to play the map from CS2 in the same way as other official maps.
Hopefully we don't have to take these steps as CS2 is getting more mature in terms of features.

### Preparation
The map generated by Hammer has an extension of \`.vpk\`, which is just an archive of build artifacts.
In order to decompress and compress \`.vpk\` files, you would need to download 7zip with a VPK format provider.

* **7-Zip**: [Download Link](https://www.7-zip.org/download.html)
* **VPK Format Provider**: [Download Link](https://github.com/SCell555/7zip-vpk/releases)

### Build and extract the map
Build the map as usual, once the build succeeds, a \`<your-addon-map-name>.vpk\` file should be generated under the directory
\`<your-drive>:\\\\SteamLibrary\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo_addons\\<your-addon-map-name>\\maps\`.

Copy \`<your-addon-map-name>.vpk\` to a temporary directory of your choice, then extract the files as shown below.

![Screenshot 1](/csmaps/tutorials/tutorial202-1.jpg)

You will notice that the archive has everything except for \`materials\`.
If you load the map right now, the textures will not render correctly as they are not even found.

![Screenshot 2](/csmaps/tutorials/tutorial202-2.jpg)

### Put in the materials and compress
Under the temporary directory where you extracted \`<your-addon-map-name>.vpk\`, create a new directory called \`materials\`.

![Screenshot 3](/csmaps/tutorials/tutorial202-3.jpg)

Find the compiled materials (not the ones you saved as \`.vmat\` as they are intended for development use only) from the directory
\`<your-drive>:\\\\SteamLibrary\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo_addons\\<your-addon-map-name>\\materials\`

From there, you will see a bunch of \`.vtex_c\` files, copy all of them (except for the folder named \`default\`) to the \`materials\` directory
you created under the temporary directory earlier.

![Screenshot 4](/csmaps/tutorials/tutorial202-4.jpg)

Go back to the temporary directory, select the two directories \`materials\` and \`maps\`,
right click for the context menu, and select \`7-Zip\`, followed by \`Add to archive\`.

![Screenshot 5](/csmaps/tutorials/tutorial202-5.jpg)

A dialog should show up, make sure the following are selected:
* **Archive**: \`<your-addon-map-name>.vpk\`
* **Archive format**: \`VPK\`
* **Compression level**: \`Store\`

![Screenshot 6](/csmaps/tutorials/tutorial202-6.jpg)

A new \`<your-addon-map-name>.vpk\` should be generated, put it to the directory
\`<your-drive>:\\\\SteamLibrary\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo\\maps\`.

### Play the map

As of now, CS2 does not allow loading non-official maps by default.
We have to bypass the blocker by creating a shortcut to launch CS2 with special options.

Make a shortcut of the application \`Steam\` on your desktop, then go to \`Properties\` by right click.

![Screenshot 7](/csmaps/tutorials/tutorial202-7.jpg)

Add the string \` -applaunch 730 -insecure\` at the end of \`Target\`.
You could also change the icon by browsing the file
\`<your-drive>:\\\\SteamLibrary\\steamapps\\common\\Counter-Strike Global Offensive\\game\\bin\\win64\\cs2.exe\`.

![Screenshot 7](/csmaps/tutorials/tutorial202-8.jpg)

Launch CS2 using the shortcut, open the console with key \`~\`, then type the following commands.
If everything is setup correctly, the console should auto-complete the map name for you.
\`\`\`
sv_cheats true
map <your-addon-map-name>
\`\`\`

![Screenshot 10](/csmaps/tutorials/tutorial202-10.jpg)

The map should now be loaded with textures, it's time to enjoy!

![Screenshot 9](/csmaps/tutorials/tutorial202-9.jpg)

`,
    creationDate: "2023-10-30",
    lastUpdateDate: "2023-12-26",
    thumbnail: "/csmaps/tutorial202.jpg",
    targetGameVersion: GameVersion.COUNTER_STRIKE_2,
    isDraft: false,
  },
  {
    title: "Generate a minimap",
    hashKey: "generate-minimap",
    content: `
**Test Content**

This is the first paragraph

This is the second paragraph

![Image 1](/csmaps/tutorial201.jpg)

## Header 2
    `,
    creationDate: "2023-10-22",
    lastUpdateDate: "2023-10-22",
    thumbnail: "/csmaps/tutorial201.jpg",
    targetGameVersion: GameVersion.COUNTER_STRIKE_2,
    isDraft: true,
  },
];
